/*
 * Selling Partner API for Listings Items
 * The Selling Partner API for Listings Items (Listings Items API) provides programmatic access to selling partner listings on Amazon. Use this API in collaboration with the Selling Partner API for Product Type Definitions, which you use to retrieve the information about Amazon product types needed to use the Listings Items API.  For more information, see the [Listings Items API Use Case Guide](doc:listings-items-api-v2021-08-01-use-case-guide).
 *
 * OpenAPI spec version: 2021-08-01
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapis;

import java.util.List;

import org.junit.Ignore;

import com.amazon.spapi.api.ListingsApi;
import com.amazon.spapi.client.ApiException;
import com.amazon.spapi.model.listingsitems.Item;
import com.google.common.collect.Lists;

/**
 * API tests for ListingsApi
 */
@Ignore
public class ListingsApiTest {

    private static final ListingsApi api = AmazonBaseSpApiTest.listingApi;

    public static String sellerId = AmazonBaseSpApiTest.sellerId;

    public static List<String> marketplaceIds = AmazonBaseSpApiTest.marketPlaceIds;

    public static List<String> includedData = Lists.newArrayList("attributes"
            , "summaries", "offers", "fulfillmentAvailability", "procurement");
    static String issueLocale = null;

    public static void main(String[] args) {
        String issueLocale = null;
        String sku = "usa#8020-01";
        try {
            Item listingsItem = api.getListingsItem(sellerId, sku, marketplaceIds, issueLocale, includedData);
            System.out.println(listingsItem);
        } catch (ApiException e) {
            e.printStackTrace();
            if (e.getMessage().equals("Not Found")) {
                System.out.println(sku + "已删除");
            }
        }
    }
}
